/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#c3c0ff",
        "surface": "#fbf8fc",
        "outline-variant": "#c3c6d7",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1b1b1e",
        "primary-fixed": "#dbe1ff",
        "inverse-primary": "#b4c5ff",
        "on-error": "#ffffff",
        "tertiary-fixed": "#ffdbcd",
        "tertiary": "#943700",
        "surface-dim": "#dcd9dd",
        "on-primary-container": "#eeefff",
        "surface-container-highest": "#e4e1e6",
        "on-primary-fixed": "#00174b",
        "surface-tint": "#0053db",
        "secondary-container": "#645efb",
        "primary-container": "#2563eb",
        "tertiary-container": "#bc4800",
        "on-tertiary-container": "#ffede6",
        "surface-container-high": "#eae7eb",
        "on-surface-variant": "#434655",
        "primary-fixed-dim": "#b4c5ff",
        "on-tertiary-fixed": "#360f00",
        "secondary-fixed": "#e2dfff",
        "surface-bright": "#fbf8fc",
        "primary": "#004ac6",
        "on-secondary-container": "#fffbff",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#003ea8",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#3323cc",
        "on-secondary-fixed": "#0f0069",
        "surface-container-low": "#f6f2f7",
        "tertiary-fixed-dim": "#ffb596",
        "surface-variant": "#e4e1e6",
        "on-surface": "#1b1b1e",
        "background": "#fbf8fc",
        "inverse-on-surface": "#f3f0f4",
        "on-tertiary-fixed-variant": "#7d2d00",
        "on-secondary": "#ffffff",
        "inverse-surface": "#303033",
        "secondary": "#4b41e1",
        "error": "#ba1a1a",
        "outline": "#737686",
        "surface-container": "#f0edf1",
        "zinc-core": "#18181B",
        "zinc-muted": "#52525B",
        "zinc-subtle": "#A1A1AA",
        "zinc-border": "#E4E4E7",
        "zinc-border-strong": "#D4D4D8",
        "zinc-canvas": "#FAFAFA",
        "zinc-hover": "#F4F4F5",
        "zinc-selection": "#EFF6FF",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "sm": "0.125rem",
        "md": "0.375rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "2xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "space-2xs": "0.125rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-base": "1rem",
        "space-lg": "1.25rem",
        "space-xl": "1.5rem",
        "space-2xl": "2rem",
        "sidebar-width": "15rem",
        "sidebar-collapsed-width": "3.5rem",
        "detail-pane-width": "20rem",
        "row-height-compact": "2rem",
        "row-height-standard": "2.5rem",
      },
      fontFamily: {
        "display": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["18px", { lineHeight: "24px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-md": ["15px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["13px", { lineHeight: "18px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "body-lg": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }],
        "code-sm": ["11px", { lineHeight: "14px", letterSpacing: "0em", fontWeight: "400" }],
      }
    },
  },
  plugins: [],
}
